### ISSUE TITLE
Normalize stacktrace diffs

### ISSUE THREAD

**Issue by JelleZijlstra** [hauntsaninja/mypy_primer#18]
Reference: https://github.com/python/mypy/pull/10686#issuecomment-905110424

It would be nice if mypy-primer didn't tell us that the stacktrace for a crash now uses "new_mypy" instead of "old_mypy" in its path, or that the version of mypy changed due to a new commit hash.

**Comment by JukkaL** [comment]
Also, we could filter out line numbers from tracebacks.

Somewhat unrelated: What about always reporting crashes, even if they happen with old mypy? These are usually something we'd want to fix quickly.

**Comment by hauntsaninja** [comment]
I pushed b4e8559 to normalise filenames. So for typeshed's CI should no longer see mypy crashes (that were not caused by the relevant typeshed change).

Given this, I'll probably add an option to always report a crash, since for mypy's CI, we're still very interested in seeing all crashes. However this is low pri:
- In practice it seems like people are good about paying attention to new crashes in PRs, which is the chief avenue I'd expect to see them. So I don't think we need to worry too much about merging a change that causes a crash and then needing reminders about it.
- I believe there are no crashes with mypy master.
- That leaves the case where one of the projects we check makes a change that causes a crash. I don't think this has happened. Most projects with crashes are from me trying to find projects where mypy breaks.
