### ISSUE TITLE
New errors in typeshed with mypy 0.820

### ISSUE THREAD

**Issue by Akuli** [hauntsaninja/mypy_primer#24]
See https://github.com/python/typeshed/pull/6599 for example. Getting two unrelated tracebacks on every pull request is a bit annoying.

**Comment by hauntsaninja** [comment]
This should actually be caused by https://github.com/python/typeshed/pull/6593

Relevant primer code is here: https://github.com/hauntsaninja/mypy_primer/blob/5d50d01ac59601f8e25f9c3f2c9382c555994928/mypy_primer.py#L1358

mypy 0.920 (unlike 0.910) does not crash on match statements. All the typeshed runs I've seen with tracebacks ran with mypy 0.910. I agree that tracebacks are annoying, but I think we shouldn't really have them going forward.

**Comment by hauntsaninja** [comment]
Looks like there was a third project that does crash with 0.920, I pushed b4e85595 to help with this
