### ISSUE TITLE
Make diff comments link to the source code on GitHub

### ISSUE THREAD

**Issue by JelleZijlstra** [hauntsaninja/mypy_primer#3]
It would be really great if mypy_primer's comments linked to the relevant line of source code for the library on GitHub (or even elsewhere), so it's easy to see context for the error.

An easier to implement but still useful version would be to link to the library's repo without linking to the exact line.

**Comment by hauntsaninja** [comment]
Concise output now contains the link to the project repo.

Linking the exact line is a little painful since:
- We'd have to munge mypy's output, which is always fragile
- I'd ideally want to link to the specific commit we ran on, but the way mypy_primer is structured makes that tricky
- Github doesn't let you do nice links within code formatting (which the CI actions use for brevity and diff highlighting)

**Comment by JelleZijlstra** [comment]
Thank you!
